functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре(название товара, рейтинг, цена со скидкой и без нее)
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен быть разработан по технологии SPA
  - Пользователь должен иметь возможность вернуться к каталожной странице из корзины
  - Пользователь должен иметь возможность удалять товары из корзины
  - Корзина должна храниться в сессии браузерва
  - На сайте должен работать постраничный вывод
  - Пользователь должен иметь возможноть сделать заказ на сайте

non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен обеспечивать безопасное соединение с платежными шлюзами
  - Сайт должен быть доступен на разных языках
  - Пользователь должен иметь возможность сбросить все фильтры товаров
  - Пользователь должен иметь возможность оплатить товар на сайте
  - Пользователь должен иметь возможность полностью очищать корзину
