functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины

non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - На сайте должна отслеживаться информация о статусе заказа
  - Сайт должен обеспечивать безопасное соединение с платежными шлюзами
  - Пользователь должен иметь возможность удалять товары из корзины
  - Сайт должен иметь страницу авторизации пользовтеля
  - Пользователь должен иметь возможность вернуться к каталожной странице из корзины
  - Корзина должна храниться в сессии браузерва