functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах

non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - На сайте должна отслеживаться информация о статусе заказа
  - Сайт должен обеспечивать безопасное соединение с платежными шлюзами
  - Пользователь должен иметь возможность удалять товары из корзины
  - Сайт должен иметь страницу авторизации пользовтеля
  - Сайт должен иметь систему лояльности
  - Пользователь должен иметь возможность вернуться к каталожной странице из корзины
  - Корзина должна храниться в сессии браузерва